[package]
authors = ["Crypto Garage"]
name = "bitcoin-test-utils"
version = "0.1.0"

[dependencies]
bitcoin = { version = "0.31.2", default-features = false }
bitcoincore-rpc = {version = "0.19"}
bitcoincore-rpc-json = {version = "0.19"}
