[package]
edition = "2021"
name = "electrs-blockchain-provider"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = {version = "0.29"}
bitcoin-test-utils = {path = "../bitcoin-test-utils"}
dlc-manager = {path = "../dlc-manager"}
lightning = {version = "0.0.113"}
lightning-block-sync = {version = "0.0.113"}
log = "0.4.14"
reqwest = {version = "0.11", features = ["blocking", "json"]}
rust-bitcoin-coin-selection = {version = "0.1.0", git = "https://github.com/p2pderivatives/rust-bitcoin-coin-selection", features = ["rand"]}
serde = {version = "*", features = ["derive"]}
serde_json = "1.0.81"
simple-wallet = {path = "../simple-wallet"}
tokio = "1"
