[package]
edition = "2018"
name = "simple-wallet"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.29"
dlc = {path = "../dlc"}
dlc-manager = {path = "../dlc-manager"}
lightning = {version = "0.0.116"}
rust-bitcoin-coin-selection = { rev = "23a6bf85", git = "https://github.com/p2pderivatives/rust-bitcoin-coin-selection", features = ["rand"]}
secp256k1-zkp = {version = "0.7.0"}

[dev-dependencies]
mocks = {path = "../mocks"}
secp256k1-zkp = {version = "0.7.0", features = ["global-context"]}
