[package]
edition = "2021"
name = "dlc-fuzz"
publish = false
version = "0.1.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
dlc-messages = {path = "../dlc-messages"}
honggfuzz = "0.5"
lightning = {version = "0.0.118" }

[workspace]
members = ["."]
