[package]
authors = ["Crypto Garage"]
edition = "2018"
name = "mocks"
version = "0.1.0"

[dependencies]
bitcoin = "0.30"
dlc = {path = "../dlc"}
dlc-manager = {path = "../dlc-manager"}
dlc-messages = {path = "../dlc-messages"}
lightning = {version = "0.0.121"}
secp256k1-zkp = {version = "0.9.2", features = ["bitcoin_hashes", "global-context", "rand", "rand-std"]}
simple-wallet = {path = "../simple-wallet"}
