[package]
authors = ["Crypto Garage"]
edition = "2018"
name = "mocks"
version = "0.1.0"

[dependencies]
bitcoin = "0.29"
dlc = {path = "../dlc"}
dlc-manager = {path = "../dlc-manager", features = ["use-serde"]}
dlc-messages = {path = "../dlc-messages"}
lightning = {version = "0.0.116"}
secp256k1-zkp = {version = "0.7.0", features = ["bitcoin_hashes", "global-context", "rand", "rand-std"]}
simple-wallet = {path = "../simple-wallet"}
